Update dependencies to Mesos 1.8.1 (#46)
### Description:
Upgrading dependencies to Mesos 1.8.1
Upgrading Pants version to 1.23.0
Added Python3.8 to Virtualbox through deadsnakes ppa
Bumped up minimum version of Vagrant to 2.2.9


### Testing Done:
Created Vagrant box
Did a vagrant up

diff --git a/pants b/pants
--- a/pants
+++ b/pants
@@ -1,99 +1,262 @@
 #!/usr/bin/env bash
-#
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#     http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
+# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
+# Licensed under the Apache License, Version 2.0 (see LICENSE).
 
 # =============================== NOTE ===============================
-# This pants bootstrap script comes from the pantsbuild/setup
-# project and is intended to be checked into your code repository so
-# that any developer can check out your code and be building it with
-# pants with no prior setup needed.
+# This ./pants bootstrap script comes from the pantsbuild/setup
+# project. It is intended to be checked into your code repository so
+# that other developers have the same setup.
+
 #
-# You can learn more here: https://pantsbuild.github.io/setup
+# Learn more here: https://www.pantsbuild.org/docs/installation
 # ====================================================================
-set -e
 
-# AURORA-1717: If the PYTHONPATH is tainted, calling `./pants` may fail
-# with `ImportError: No module named pants.bin.pants_exe`
-unset PYTHONPATH
+set -eou pipefail
 
-PYTHON=${PYTHON:-$(which python2.7)}
+PYTHON_BIN_NAME="${PYTHON:-unspecified}"
 
-PANTS_HOME="${PANTS_HOME:-${HOME}/.cache/pants/setup}"
+# Set one of these to specify a non-standard location for this script to read the pants version from.
+# NB: This will *not* cause Pants itself to use this location as a config file.
+#     You can use PANTS_CONFIG_FILES or --pants-config-files to do so.
+PANTS_INI=${PANTS_INI:-pants.ini}
+PANTS_TOML=${PANTS_TOML:-pants.toml}
+
+# NOTE: To use an unreleased version of Pants from the pantsbuild/pants master branch,
+#  locate the master branch SHA, set PANTS_SHA=<SHA> in the environment, and run this script as usual.
+#
+# E.g., PANTS_SHA=725fdaf504237190f6787dda3d72c39010a4c574 ./pants --version
+
+PANTS_BIN_NAME="${PANTS_BIN_NAME:-$0}"
+
+PANTS_HOME="${PANTS_HOME:-${XDG_CACHE_HOME:-$HOME/.cache}/pants/setup}"
+# If given a relative path, we fix it to be absolute.
+if [[ "$PANTS_HOME" != /* ]]; then
+  PANTS_HOME="${PWD}/${PANTS_HOME}"
+fi
+
 PANTS_BOOTSTRAP="${PANTS_HOME}/bootstrap-$(uname -s)-$(uname -m)"
 
-VENV_VERSION=16.6.1
+VENV_VERSION=${VENV_VERSION:-16.4.3}
 
 VENV_PACKAGE=virtualenv-${VENV_VERSION}
 VENV_TARBALL=${VENV_PACKAGE}.tar.gz
 
-# The high-level flow:
-# 1.) Grab pants version from pants.ini or default to latest.
-# 2.) Check for a venv via a naming/path convention and execute if found.
-# 3.) Otherwise create venv and re-exec self.
-#
-# After that pants itself will handle making sure any requested plugins
-# are installed and up to date.
+COLOR_RED="\x1b[31m"
+COLOR_GREEN="\x1b[32m"
+COLOR_RESET="\x1b[0m"
+
+function log() {
+  echo -e "$@" 1>&2
+}
+
+function die() {
+  (($# > 0)) && log "${COLOR_RED}$*${COLOR_RESET}"
+  exit 1
+}
+
+function green() {
+  (($# > 0)) && log "${COLOR_GREEN}$*${COLOR_RESET}"
+}
 
 function tempdir {
   mktemp -d "$1"/pants.XXXXXX
+}
+
+function get_exe_path_or_die {
+  exe="$1"
+  if ! command -v "${exe}"; then
+    die "Could not find ${exe}. Please ensure ${exe} is on your PATH."
+  fi
+}
+
+pants_config_file=""
+if [[ -f "${PANTS_INI}" ]]; then
+  pants_config_file="${PANTS_INI}"
+fi
+if [[ -f "${PANTS_TOML}" ]]; then
+  pants_config_file="${PANTS_TOML}"
+fi
+
+function get_pants_config_value {
+  config_key="$1"
+  optional_space="[[:space:]]*"
+  if [[ "${pants_config_file}" == *.ini ]]; then
+    valid_delimiters="[:=]"
+    prefix="^${config_key}${optional_space}${valid_delimiters}${optional_space}"
+    sed -ne "/${prefix}/ s#${prefix}##p" "${PANTS_INI}" && return 0
+  fi
+  if [[ "${pants_config_file}" == *.toml ]]; then
+    prefix="^${config_key}${optional_space}=${optional_space}"
+    raw_value="$(sed -ne "/${prefix}/ s#${prefix}##p" "${PANTS_TOML}")"
+    echo "${raw_value}"  | tr -d \"\' && return 0
+  fi
+  return 0
+}
+
+function get_python_major_minor_version {
+  python_exe="$1"
+  "$python_exe" <<EOF
+import sys
+major_minor_version = ''.join(str(version_num) for version_num in sys.version_info[0:2])
+print(major_minor_version)
+EOF
+}
+
+# The high-level flow:
+# 1.) Resolve the Python interpreter, first reading from the env var $PYTHON,
+#     then defaulting to Python 3.6+.
+# 2.) Resolve the Pants version from config or from the latest stable
+#     release to PyPI, so that we know what to name the venv (virtual environment) folder and what
+#     to install with Pip.
+# 3.) Check if the venv already exists via a naming convention, and create the venv if not found.
+# 4.) Execute Pants with the resolved Python interpreter and venv.
+#
+# After that, Pants itself will handle making sure any requested plugins
+# are installed and up to date.
+
+function determine_pants_version {
+
+  if [ -n "${PANTS_SHA:-}" ]; then
+    # get_version_for_sha will echo the version, thus "returning" it from this function.
+    get_version_for_sha "$PANTS_SHA"
+    return
+  fi
+
+  python="$1"
+
+  pants_version="$(get_pants_config_value 'pants_version')"
+  if [[ -z "${pants_version}" ]]; then
+    pants_version="$(curl -sSL https://pypi.python.org/pypi/pantsbuild.pants/json |
+      "${python}" -c "import json, sys; print(json.load(sys.stdin)['info']['version'])")"
+  fi
+  pants_major_version="$(echo "${pants_version}" | cut -d '.' -f1)"
+  pants_minor_version="$(echo "${pants_version}" | cut -d '.' -f2)"
+  if [[ "${pants_major_version}" -eq 1 && "${pants_minor_version}" -le 22 ]]; then
+    die "This version of the \`./pants\` script does not work with Pants <= 1.22.0. Instead,
+either upgrade your \`pants_version\` or use the version of the \`./pants\` script at
+https://raw.githubusercontent.com/pantsbuild/setup/d1da382f6de0420940ec6007a39cba87c21075c6/pants."
+  fi
+  echo "${pants_version}"
+}
+
+function determine_default_python_exe {
+  for version in '3.6' '3.7' '3.8' '3.9'; do
+    interpreter_path="$(command -v "python${version}")"
+    if [[ -z "${interpreter_path}" ]]; then
+      continue
+    fi
+    # Check if the Python version is installed via Pyenv but not activated.
+    if [[ "$("${interpreter_path}" --version 2>&1 > /dev/null)" == "pyenv: python${version}"* ]]; then
+      continue
+    fi
+    echo "${interpreter_path}" && return 0
+  done
+}
+
+function determine_python_exe {
+  if [[ "${PYTHON_BIN_NAME}" != 'unspecified' ]]; then
+    python_bin_name="${PYTHON_BIN_NAME}"
+  else
+    python_bin_name="$(determine_default_python_exe)"
+    if [[ -z "${python_bin_name}" ]]; then
+      die "No valid Python interpreter found. Pants requires Python 3.6+ to run."
+    fi
+  fi
+  python_exe="$(get_exe_path_or_die "${python_bin_name}")"
+  major_minor_version="$(get_python_major_minor_version "${python_exe}")"
+  for valid_version in '36' '37' '38' '39'; do
+    if [[ "${major_minor_version}" == "${valid_version}" ]]; then
+      echo "${python_exe}" && return 0
+    fi
+  done
+  die "Invalid Python interpreter version for ${python_exe}. Pants requires Python 3.6+ to run."
 }
 
 # TODO(John Sirois): GC race loser tmp dirs leftover from bootstrap_XXX
 # functions.  Any tmp dir w/o a symlink pointing to it can go.
 
 function bootstrap_venv {
-  if [[ ! -d "${PANTS_BOOTSTRAP}/${VENV_PACKAGE}" ]]
-  then
+  if [[ ! -d "${PANTS_BOOTSTRAP}/${VENV_PACKAGE}" ]]; then
     (
-      mkdir -p "${PANTS_BOOTSTRAP}" && \
-      staging_dir=$(tempdir "${PANTS_BOOTSTRAP}") && \
-      cd "${staging_dir}" && \
-      curl -LO https://pypi.io/packages/source/v/virtualenv/${VENV_TARBALL} && \
-      tar -xzf ${VENV_TARBALL} && \
-      ln -s "${staging_dir}/${VENV_PACKAGE}" "${staging_dir}/latest" && \
+      mkdir -p "${PANTS_BOOTSTRAP}"
+      staging_dir=$(tempdir "${PANTS_BOOTSTRAP}")
+      cd "${staging_dir}"
+      curl -LO "https://pypi.io/packages/source/v/virtualenv/${VENV_TARBALL}"
+      tar -xzf "${VENV_TARBALL}"
+      ln -s "${staging_dir}/${VENV_PACKAGE}" "${staging_dir}/latest"
       mv "${staging_dir}/latest" "${PANTS_BOOTSTRAP}/${VENV_PACKAGE}"
     ) 1>&2
   fi
   echo "${PANTS_BOOTSTRAP}/${VENV_PACKAGE}"
 }
 
-function bootstrap_pants {
-  pants_requirement="pantsbuild.pants"
-  pants_version=$(
-    grep -E "^[[:space:]]*pants_version" pants.ini 2>/dev/null | \
-      cut -f2 -d: | tr -d " "
-  )
-  if [[ -n "${pants_version}" ]]
-  then
-    pants_requirement="${pants_requirement}==${pants_version}"
-  else
-    pants_version="unspecified"
-  fi
+function find_links_url {
+  local pants_version="$1"
+  local pants_sha="$2"
 
-  if [[ ! -d "${PANTS_BOOTSTRAP}/${pants_version}" ]]
-  then
-    (
-      venv_path="$(bootstrap_venv)" && \
-      staging_dir=$(tempdir "${PANTS_BOOTSTRAP}") && \
-      "${PYTHON}" "${venv_path}/virtualenv.py" --no-download "${staging_dir}/install" && \
-      "${staging_dir}/install/bin/python" "${staging_dir}/install/bin/pip" install "${pants_requirement}" && \
-      ln -s "${staging_dir}/install" "${staging_dir}/${pants_version}" && \
-      mv "${staging_dir}/${pants_version}" "${PANTS_BOOTSTRAP}/${pants_version}"
-    ) 1>&2
-  fi
-  echo "${PANTS_BOOTSTRAP}/${pants_version}"
+  echo -n "https://binaries.pantsbuild.org/wheels/pantsbuild.pants/${pants_sha}/${pants_version/+/%2B}/index.html"
 }
 
-pants_dir=$(bootstrap_pants) && \
-exec "${pants_dir}/bin/python" "${pants_dir}/bin/pants" "$@"
+function get_version_for_sha {
+  local sha="$1"
+
+  # Retrieve the Pants version associated with this commit.
+  local pants_version
+  pants_version="$(curl --fail -sL "https://raw.githubusercontent.com/pantsbuild/pants/${sha}/src/python/pants/VERSION")"
+
+  # Construct the version as the release version from src/python/pants/VERSION, plus the string `+gitXXXXXXXX`,
+  # where the XXXXXXXX is the first 8 characters of the SHA.
+  echo "${pants_version}+git${sha:0:8}"
+}
+
+function bootstrap_pants {
+  pants_version="$1"
+  python="$2"
+  pants_sha="${3:-}"
+
+  pants_requirement="pantsbuild.pants==${pants_version}"
+  if [[ -z "${pants_sha}" ]]; then
+    maybe_find_links=""
+  else
+    maybe_find_links="--find-links=$(find_links_url "${pants_version}" "${pants_sha}")"
+   fi
+  python_major_minor_version="$(get_python_major_minor_version "${python}")"
+  target_folder_name="${pants_version}_py${python_major_minor_version}"
+
+  if [[ ! -d "${PANTS_BOOTSTRAP}/${target_folder_name}" ]]; then
+    (
+      venv_path="$(bootstrap_venv)"
+      staging_dir=$(tempdir "${PANTS_BOOTSTRAP}")
+      # shellcheck disable=SC2086
+      "${python}" "${venv_path}/virtualenv.py" --no-download "${staging_dir}/install" && \
+      "${staging_dir}/install/bin/pip" install -U pip && \
+      "${staging_dir}/install/bin/pip" install ${maybe_find_links} --progress-bar off "${pants_requirement}" && \
+      ln -s "${staging_dir}/install" "${staging_dir}/${target_folder_name}" && \
+      mv "${staging_dir}/${target_folder_name}" "${PANTS_BOOTSTRAP}/${target_folder_name}" && \
+      green "New virtual environment successfully created at ${PANTS_BOOTSTRAP}/${target_folder_name}."
+    ) 1>&2
+  fi
+  echo "${PANTS_BOOTSTRAP}/${target_folder_name}"
+}
+
+# Ensure we operate from the context of the ./pants buildroot.
+cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
+python="$(determine_python_exe)"
+pants_version="$(determine_pants_version "${python}")"
+pants_dir="$(bootstrap_pants "${pants_version}" "${python}" "${PANTS_SHA:-}")"
+pants_python="${pants_dir}/bin/python"
+pants_binary="${pants_dir}/bin/pants"
+pants_extra_args=""
+if [[ -n "${PANTS_SHA:-}" ]]; then
+  pants_extra_args="${pants_extra_args} --python-repos-repos=$(find_links_url "$pants_version" "$PANTS_SHA")"
+fi
+
+# We set the env var no_proxy to '*', to work around an issue with urllib using non
+# async-signal-safe syscalls after we fork a process that has already spawned threads.
+#
+# See https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/
+export no_proxy='*'
+
+# shellcheck disable=SC2086
+exec "${pants_python}" "${pants_binary}" ${pants_extra_args} \
+  --pants-bin-name="${PANTS_BIN_NAME}" --pants-version=${pants_version} "$@"
